version: '3.8'

services:
  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "corepack enable && pnpm install && cd packages/backend && pnpm tsx src/db/database.ts"
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=development