services:
  backend:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/backend/node_modules
    command: sh -c "pnpm install && pnpm rebuild better-sqlite3 && tail -f /dev/null"
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=development
      - CI=true